# Generated by Django 4.1 on 2022-08-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="labels",
            field=models.ManyToManyField(
                blank=True, default="None", to="web.labels", verbose_name="Метка"
            ),
        ),
    ]
