# Generated by Django 4.1 on 2022-08-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_tasks_creator_alter_tasks_executor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labels",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="statuses",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
