# Generated by Django 4.1 on 2022-08-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
