# Generated by Django 4.1 on 2022-08-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_labels_name_alter_statuses_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuses",
            name="name",
            field=models.CharField(
                error_messages={"unique": "This email has already been registered."},
                max_length=200,
                unique=True,
            ),
        ),
    ]
