# Generated by Django 4.1 on 2022-08-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_statuses_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuses",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
