# Generated by Django 4.0.6 on 2022-08-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
