# Generated by Django 4.1 on 2022-08-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_tasks_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="tasks",
            name="labels",
            field=models.ManyToManyField(to="web.labels"),
        ),
    ]
